import 'bootstrap/dist/css/bootstrap.min.css'
import '@/app/_styles/globals.scss'
import Providers from './providers'

import RootClientLayout from './_components/RootClientLayout'

export const metadata = {
  title: 'Bark & Bijou',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <RootClientLayout>{children}</RootClientLayout>
        </Providers>
      </body>
    </html>
  )
}
